name: estrella_roja_qa_bot
description: "Estrella Roja - Bot de Compra de Boletos - Interfaz de Usuario para QA"
publish_to: 'none'

version: 1.2.4+7

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  process_run: ^1.2.0
  path_provider: ^2.1.4
  path: ^1.9.0
  shared_preferences: ^2.3.2
  flutter_secure_storage: ^9.2.2
  file_picker: ^8.1.4
  xterm: ^4.0.0
  provider: ^6.1.2
  flutter_form_builder: ^10.2.0
  form_builder_validators: ^11.0.0
  json_annotation: ^4.9.0
  flutter_animate: ^4.5.0
  google_fonts: ^6.2.1
  http: ^1.2.2
  archive: ^3.6.1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
